# -*- coding: utf-8 -*-
"""lms_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8OMagX7eXR31szPT2jkemUbXkPqG3cg
"""

import warnings
warnings.filterwarnings('ignore')

# Install required packages (without Google GenAI)
!pip install langchain langchain-core langchain-community langchain-groq

import os
from IPython.display import display, Markdown

# LangChain & Groq
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.output_parsers import StrOutputParser
from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.runnables import RunnablePassthrough

print("All libraries imported successfully!")

# Replace this string with your real Groq API key
GROQ_API_KEY = "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"
os.environ["GROQ_API_KEY"] = GROQ_API_KEY

print("Groq API key configured")

llm = ChatGroq(
    model_name="llama-3.1-8b-instant",
    temperature=0.2
)

response = llm.invoke("Hello Gemini! Explain RAG in artificial intelligence simple words.")
print(response.content)

SYSTEM_PROMPT = """
You are **QUANTUM ASSISTANT CHATBOT **, a friendly, caring, and motivating academic companion for students in Pakistan 🇵🇰.

🎯 Your main goal:
Help students improve their marks, reduce study stress, build confidence, and succeed academically — even if they feel weak, demotivated, or burdened by studies.

━━━━━━━━━━━━━━━━━━
💙 Emotional Support & Motivation
━━━━━━━━━━━━━━━━━━
- Be kind, patient, non-judgmental, and encouraging.
- If a student has low marks, NEVER shame them.
- Motivate students by:
  • Explaining that low marks are temporary
  • Encouraging consistency, practice, and smart study
  • Breaking big problems into small achievable steps
- If a student feels depressed, stressed, or overloaded:
  • Acknowledge their feelings respectfully
  • Offer calm study strategies and time management tips
  • Encourage short breaks, positive thinking, and asking for academic help
- Never give medical or psychological treatment advice.

━━━━━━━━━━━━━━━━━━
📘 Academic Help & Lecture Understanding
━━━━━━━━━━━━━━━━━━
- Solve **Math problems step-by-step** in simple language.
- Explain **Science concepts** using:
  • Easy examples
  • Real-life connections
  • Simple diagrams (when helpful)
- Improve **English skills**:
  • Grammar
  • Vocabulary
  • Sentence structure
  • Essay & paragraph writing
- Help students understand **ANY type of lecture**, including:
  • School classroom lectures
  • Online or recorded lectures
  • Fast or confusing teacher explanations
  • Missed classes
- If a student says:
  “Mujhe lecture samajh nahi aaya”
  → Re-explain the topic slowly, from basics, in an easy and friendly way.
- Adjust explanation level based on student class:
  • Primary
  • Middle
  • Matric
  • Inter

━━━━━━━━━━━━━━━━━━
🚀 Marks Improvement Strategy
━━━━━━━━━━━━━━━━━━
- Suggest:
  • Daily and weekly study plans
  • Smart revision techniques
  • Exam preparation tips
  • Past paper solving strategies
- Help students identify:
  • Weak subjects
  • Common mistakes
  • High-scoring and easy topics
- Encourage realistic goal-setting (weekly & monthly).

━━━━━━━━━━━━━━━━━━
🎓 Career & Future Guidance
━━━━━━━━━━━━━━━━━━
- Guide students gently toward future paths:
  • Pre-Medical
  • Engineering
  • Computer Science
  • Business
  • Arts
- Encourage focus on:
  • Skills
  • Consistency
  • Learning mindset (not just marks)
- Explain career paths in simple, motivating language.

━━━━━━━━━━━━━━━━━━
🔬 Science & Learning Motivation
━━━━━━━━━━━━━━━━━━
- Share interesting science facts, discoveries, inventions, and technology trends.
- Build curiosity and love for learning beyond textbooks.

━━━━━━━━━━━━━━━━━━
📺 Free Learning Resources
━━━━━━━━━━━━━━━━━━
- Recommend public educational platforms when helpful:
  • Campus X: https://www.youtube.com/@campusx-official
- Never promote paid or private coaching.

━━━━━━━━━━━━━━━━━━
🗣️ Communication Style
━━━━━━━━━━━━━━━━━━
- Greet students politely and warmly.
- Use **English or Roman Urdu** depending on student preference.
- Sound like a supportive teacher + caring mentor.
- Keep explanations:
  • Simple
  • Clear
  • Confidence-boosting
- Ask gentle clarifying questions if:
  • Subject
  • Class
  • Topic
  • Lecture source
  is unclear.

━━━━━━━━━━━━━━━━━━
✅ Safety & Ethics
━━━━━━━━━━━━━━━━━━
- Be respectful and abuse-free.
- Never invent private contact details or personal information.
- Share only educational and publicly available information.

━━━━━━━━━━━━━━━━━━
🌟 Ending Rule
━━━━━━━━━━━━━━━━━━
End EVERY response with:
“Aap bohat acha kar rahe ho, practice jari rakhein 🌟”

"""

prompt = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}")
])

chain = prompt | llm | StrOutputParser()

store = {}

def get_session_history(session_id: str):
    if session_id not in store:
        store[session_id] = InMemoryChatMessageHistory()
    return store[session_id]

chain_with_memory = RunnableWithMessageHistory(
    chain,
    get_session_history,
    input_messages_key="input",
    history_messages_key="chat_history"
)

response = chain_with_memory.invoke(
    {"input": "Hello! Can you help me with maths?"},
    config={"configurable": {"session_id": "student_1"}}
)

print(response)

from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
store = {}

def get_session_history(session_id: str):
    if session_id not in store:
        store[session_id] = InMemoryChatMessageHistory()
    return store[session_id]
chain_with_memory = RunnableWithMessageHistory(
    chain,
    get_session_history,
    input_messages_key="input",
    history_messages_key="chat_history",
)
response = chain_with_memory.invoke(
    {"input": "Hello, mujhe maths samajh nahi aa rahi"},
    config={"configurable": {"session_id": "user_1"}}
)

print(response)

# Create the prompt template with system prompt
prompt = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    MessagesPlaceholder(variable_name="chat_history"),  # This will contain the full history
    MessagesPlaceholder(variable_name="recent_history"),  # This will contain just recent messages
    ("human", "{input}")
])

print("Chat prompt template created!")

from langchain_core.runnables import RunnablePassthrough

chain = RunnableWithMessageHistory(
    prompt | llm | StrOutputParser(),
    get_session_history,
    input_messages_key="input",
    history_messages_key="chat_history"
)
# Build the chain using LCEL (LangChain Expression Language)
def get_chat_history(input_dict):
    # Extract the list of messages from the dictionary returned by memory
    return buffer_memory.load_memory_variables({})["chat_history"]

def get_recent_history(input_dict):
    # Extract the list of messages from the dictionary returned by window memory
    return window_memory.load_memory_variables({})["recent_history"]

chain = (
    {
        "input": RunnablePassthrough(),
        "chat_history": get_chat_history,
        "recent_history": get_recent_history
    }
    | prompt
    | llm
    | StrOutputParser()
)

print("LCEL chain configured!")

def chat_with_bot():
    print("Welcome to QUANTUM STUDENT CHATBOT 🌟")
    print("Type 'exit' to quit.\n")

    session_id = "student_1"

    while True:
        user_input = input("You: ")

        if user_input.lower() in ["exit", "quit"]:
            print("Quantum Chatbot: Shukriya! Aap bohat acha kar rahe ho, practice jari rakhein 🌟")
            break

        # Auto-detect subject keywords
        subject = None
        math_keywords = ["math", "mathematics", "algebra", "geometry", "equation", "calculate", "solve"]
        science_keywords = ["science", "physics", "chemistry", "biology", "experiment"]
        english_keywords = ["english", "grammar", "reading", "vocabulary", "essay"]

        text_lower = user_input.lower()

        if any(word in text_lower for word in math_keywords):
            subject = "math"
        elif any(word in text_lower for word in science_keywords):
            subject = "science"
        elif any(word in text_lower for word in english_keywords):
            subject = "english"

        # Handle video request (NO specific channels promoted)
        if "video" in text_lower or "youtube" in text_lower:
            print(
                "Quantum Chatbot: Main aapko topic yahin step-by-step samjha sakta hoon 😊\n"
                "Agar phir bhi video chahiye, to YouTube par topic name + class search karein.\n"
                "Example: 'Algebra equations class 9'\n\n"
                "Aap bohat acha kar rahe ho, practice jari rakhein 🌟"
            )
            continue

        # For Math problems → enforce step-by-step solving
        if subject == "math":
            user_input = "Solve this step-by-step from basics: " + user_input

        # Send query to model with memory
        response = chain_with_memory.invoke(
            {"input": user_input},
            config={"configurable": {"session_id": session_id}}
        )

        # Extract text safely
        response_text = response.content if hasattr(response, "content") else str(response)

        print(f"\nQuantum Chatbot: {response_text}\n")


# Run the chatbot
chat_with_bot()

